/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author manager
 */
public class TelaCalc_GUI extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalc_GUI
     */
    public TelaCalc_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MAIS_BTN = new javax.swing.JButton();
        MENOS_BTN = new javax.swing.JButton();
        DIVIDIDO_BTN = new javax.swing.JButton();
        MULT_BTN = new javax.swing.JButton();
        V1_INT = new javax.swing.JTextField();
        V2_INT = new javax.swing.JTextField();
        RES_INT = new javax.swing.JTextField();
        VAZIO = new javax.swing.JButton();
        SAIR_BTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Valor 1:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 80, 70, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor 2:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 150, 70, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Resultado:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 230, 100, 20);

        MAIS_BTN.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        MAIS_BTN.setText("+");
        MAIS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAIS_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(MAIS_BTN);
        MAIS_BTN.setBounds(30, 340, 50, 40);

        MENOS_BTN.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        MENOS_BTN.setText("-");
        MENOS_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENOS_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(MENOS_BTN);
        MENOS_BTN.setBounds(90, 340, 50, 40);

        DIVIDIDO_BTN.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        DIVIDIDO_BTN.setText("%");
        DIVIDIDO_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVIDIDO_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(DIVIDIDO_BTN);
        DIVIDIDO_BTN.setBounds(150, 340, 50, 40);

        MULT_BTN.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        MULT_BTN.setText("X");
        MULT_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULT_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(MULT_BTN);
        MULT_BTN.setBounds(210, 340, 50, 40);

        V1_INT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V1_INTActionPerformed(evt);
            }
        });
        jPanel1.add(V1_INT);
        V1_INT.setBounds(70, 100, 160, 30);

        V2_INT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V2_INTActionPerformed(evt);
            }
        });
        jPanel1.add(V2_INT);
        V2_INT.setBounds(70, 170, 160, 30);

        RES_INT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RES_INTActionPerformed(evt);
            }
        });
        jPanel1.add(RES_INT);
        RES_INT.setBounds(70, 250, 160, 30);

        VAZIO.setText("C");
        VAZIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAZIOActionPerformed(evt);
            }
        });
        jPanel1.add(VAZIO);
        VAZIO.setBounds(100, 290, 100, 30);

        SAIR_BTN.setBackground(new java.awt.Color(255, 0, 0));
        SAIR_BTN.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SAIR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        SAIR_BTN.setText("x");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(SAIR_BTN);
        SAIR_BTN.setBounds(250, 10, 40, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 10, 180, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-180, -80, 870, 660);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 400);

        setSize(new java.awt.Dimension(300, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MAIS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAIS_BTNActionPerformed
        Model.funcao_DAO.soma();
        RES_INT.setText(String.valueOf(Model.funcao_DAO.rest));
    }//GEN-LAST:event_MAIS_BTNActionPerformed

    private void V1_INTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V1_INTActionPerformed
        String valor = V1_INT.getText();
    }//GEN-LAST:event_V1_INTActionPerformed

    private void V2_INTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V2_INTActionPerformed
        String valor1 = V2_INT.getText();
    }//GEN-LAST:event_V2_INTActionPerformed

    private void RES_INTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RES_INTActionPerformed
        
    }//GEN-LAST:event_RES_INTActionPerformed

    private void MENOS_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENOS_BTNActionPerformed
        Model.funcao_DAO.sub();
        RES_INT.setText(String.valueOf(Model.funcao_DAO.rest));
    }//GEN-LAST:event_MENOS_BTNActionPerformed

    private void DIVIDIDO_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVIDIDO_BTNActionPerformed
        Model.funcao_DAO.div();
        RES_INT.setText(String.valueOf(Model.funcao_DAO.rest));
    }//GEN-LAST:event_DIVIDIDO_BTNActionPerformed

    private void MULT_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULT_BTNActionPerformed
        Model.funcao_DAO.multi();
        RES_INT.setText(String.valueOf(Model.funcao_DAO.rest));
    }//GEN-LAST:event_MULT_BTNActionPerformed

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    private void VAZIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VAZIOActionPerformed
        RES_INT.setText("");
        V1_INT.setText("");
        V2_INT.setText("");
    }//GEN-LAST:event_VAZIOActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalc_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalc_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DIVIDIDO_BTN;
    private javax.swing.JButton MAIS_BTN;
    private javax.swing.JButton MENOS_BTN;
    private javax.swing.JButton MULT_BTN;
    public static javax.swing.JTextField RES_INT;
    private javax.swing.JButton SAIR_BTN;
    public static javax.swing.JTextField V1_INT;
    public static javax.swing.JTextField V2_INT;
    private javax.swing.JButton VAZIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
